
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("d8c2b880-c85e-44d2-adc7-2f27b72b289d")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("COFABONIDatabaseModel", "FK_DetailTransaction_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Product), "DetailTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetailTransaction), True)>
<Assembly: EdmRelationshipAttribute("COFABONIDatabaseModel", "FK_HeaderTransaction_MsUser", "MsUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(MsUser), "HeaderTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(HeaderTransaction), True)>
<Assembly: EdmRelationshipAttribute("COFABONIDatabaseModel", "FK_DetailTransaction_HeaderTransaction", "HeaderTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(HeaderTransaction), "DetailTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DetailTransaction), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class COFABONIDatabaseEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new COFABONIDatabaseEntities object using the connection string found in the 'COFABONIDatabaseEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=COFABONIDatabaseEntities", "COFABONIDatabaseEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new COFABONIDatabaseEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "COFABONIDatabaseEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new COFABONIDatabaseEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "COFABONIDatabaseEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property MsUsers() As ObjectSet(Of MsUser)
        Get
            If (_MsUsers Is Nothing) Then
                _MsUsers = MyBase.CreateObjectSet(Of MsUser)("MsUsers")
            End If
            Return _MsUsers
        End Get
    End Property

    Private _MsUsers As ObjectSet(Of MsUser)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Products() As ObjectSet(Of Product)
        Get
            If (_Products Is Nothing) Then
                _Products = MyBase.CreateObjectSet(Of Product)("Products")
            End If
            Return _Products
        End Get
    End Property

    Private _Products As ObjectSet(Of Product)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DetailTransactions() As ObjectSet(Of DetailTransaction)
        Get
            If (_DetailTransactions Is Nothing) Then
                _DetailTransactions = MyBase.CreateObjectSet(Of DetailTransaction)("DetailTransactions")
            End If
            Return _DetailTransactions
        End Get
    End Property

    Private _DetailTransactions As ObjectSet(Of DetailTransaction)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property HeaderTransactions() As ObjectSet(Of HeaderTransaction)
        Get
            If (_HeaderTransactions Is Nothing) Then
                _HeaderTransactions = MyBase.CreateObjectSet(Of HeaderTransaction)("HeaderTransactions")
            End If
            Return _HeaderTransactions
        End Get
    End Property

    Private _HeaderTransactions As ObjectSet(Of HeaderTransaction)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the MsUsers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToMsUsers(ByVal msUser As MsUser)
        MyBase.AddObject("MsUsers", msUser)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToProducts(ByVal product As Product)
        MyBase.AddObject("Products", product)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DetailTransactions EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDetailTransactions(ByVal detailTransaction As DetailTransaction)
        MyBase.AddObject("DetailTransactions", detailTransaction)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the HeaderTransactions EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToHeaderTransactions(ByVal headerTransaction As HeaderTransaction)
        MyBase.AddObject("HeaderTransactions", headerTransaction)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="COFABONIDatabaseModel", Name:="DetailTransaction")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DetailTransaction
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DetailTransaction object.
    ''' </summary>
    ''' <param name="productId">Initial value of the ProductId property.</param>
    ''' <param name="quantity">Initial value of the Quantity property.</param>
    ''' <param name="transactionId">Initial value of the TransactionId property.</param>
    Public Shared Function CreateDetailTransaction(productId As Global.System.Byte, quantity As Global.System.Int32, transactionId As Global.System.Byte) As DetailTransaction
        Dim detailTransaction as DetailTransaction = New DetailTransaction
        detailTransaction.ProductId = productId
        detailTransaction.Quantity = quantity
        detailTransaction.TransactionId = transactionId
        Return detailTransaction
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ProductId() As Global.System.Byte
        Get
            Return _ProductId
        End Get
        Set
            If (_ProductId <> Value) Then
                OnProductIdChanging(value)
                ReportPropertyChanging("ProductId")
                _ProductId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ProductId")
                OnProductIdChanged()
            End If
        End Set
    End Property

    Private _ProductId As Global.System.Byte
    Private Partial Sub OnProductIdChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnProductIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Quantity() As Global.System.Int32
        Get
            Return _Quantity
        End Get
        Set
            OnQuantityChanging(value)
            ReportPropertyChanging("Quantity")
            _Quantity = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Quantity")
            OnQuantityChanged()
        End Set
    End Property

    Private _Quantity As Global.System.Int32
    Private Partial Sub OnQuantityChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnQuantityChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TransactionId() As Global.System.Byte
        Get
            Return _TransactionId
        End Get
        Set
            If (_TransactionId <> Value) Then
                OnTransactionIdChanging(value)
                ReportPropertyChanging("TransactionId")
                _TransactionId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("TransactionId")
                OnTransactionIdChanged()
            End If
        End Set
    End Property

    Private _TransactionId As Global.System.Byte
    Private Partial Sub OnTransactionIdChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnTransactionIdChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("COFABONIDatabaseModel", "FK_DetailTransaction_Product", "Product")>
    Public Property Product() As Product
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("COFABONIDatabaseModel.FK_DetailTransaction_Product", "Product").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("COFABONIDatabaseModel.FK_DetailTransaction_Product", "Product").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property ProductReference() As EntityReference(Of Product)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Product)("COFABONIDatabaseModel.FK_DetailTransaction_Product", "Product")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Product)("COFABONIDatabaseModel.FK_DetailTransaction_Product", "Product", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("COFABONIDatabaseModel", "FK_DetailTransaction_HeaderTransaction", "HeaderTransaction")>
    Public Property HeaderTransaction() As HeaderTransaction
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of HeaderTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_HeaderTransaction", "HeaderTransaction").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of HeaderTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_HeaderTransaction", "HeaderTransaction").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property HeaderTransactionReference() As EntityReference(Of HeaderTransaction)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of HeaderTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_HeaderTransaction", "HeaderTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of HeaderTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_HeaderTransaction", "HeaderTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="COFABONIDatabaseModel", Name:="HeaderTransaction")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class HeaderTransaction
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new HeaderTransaction object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="userId">Initial value of the UserId property.</param>
    ''' <param name="date">Initial value of the Date property.</param>
    Public Shared Function CreateHeaderTransaction(id As Global.System.Byte, userId As Global.System.Byte, [date] As Global.System.DateTime) As HeaderTransaction
        Dim headerTransaction as HeaderTransaction = New HeaderTransaction
        headerTransaction.Id = id
        headerTransaction.UserId = userId
        headerTransaction.[Date] = [date]
        Return headerTransaction
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Byte
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Byte
    Private Partial Sub OnIdChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UserId() As Global.System.Byte
        Get
            Return _UserId
        End Get
        Set
            OnUserIdChanging(value)
            ReportPropertyChanging("UserId")
            _UserId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserId")
            OnUserIdChanged()
        End Set
    End Property

    Private _UserId As Global.System.Byte
    Private Partial Sub OnUserIdChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnUserIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Date]() As Global.System.DateTime
        Get
            Return _Date
        End Get
        Set
            OnDateChanging(value)
            ReportPropertyChanging("Date")
            _Date = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Date")
            OnDateChanged()
        End Set
    End Property

    Private _Date As Global.System.DateTime
    Private Partial Sub OnDateChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDateChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("COFABONIDatabaseModel", "FK_HeaderTransaction_MsUser", "MsUser")>
    Public Property MsUser() As MsUser
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsUser)("COFABONIDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsUser)("COFABONIDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MsUserReference() As EntityReference(Of MsUser)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MsUser)("COFABONIDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MsUser)("COFABONIDatabaseModel.FK_HeaderTransaction_MsUser", "MsUser", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("COFABONIDatabaseModel", "FK_DetailTransaction_HeaderTransaction", "DetailTransaction")>
     Public Property DetailTransactions() As EntityCollection(Of DetailTransaction)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetailTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_HeaderTransaction", "DetailTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetailTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_HeaderTransaction", "DetailTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="COFABONIDatabaseModel", Name:="MsUser")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MsUser
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new MsUser object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="username">Initial value of the Username property.</param>
    ''' <param name="password">Initial value of the Password property.</param>
    Public Shared Function CreateMsUser(id As Global.System.Byte, username As Global.System.String, password As Global.System.String) As MsUser
        Dim msUser as MsUser = New MsUser
        msUser.Id = id
        msUser.Username = username
        msUser.Password = password
        Return msUser
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Byte
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Byte
    Private Partial Sub OnIdChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Username() As Global.System.String
        Get
            Return _Username
        End Get
        Set
            OnUsernameChanging(value)
            ReportPropertyChanging("Username")
            _Username = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Username")
            OnUsernameChanged()
        End Set
    End Property

    Private _Username As Global.System.String
    Private Partial Sub OnUsernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUsernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("COFABONIDatabaseModel", "FK_HeaderTransaction_MsUser", "HeaderTransaction")>
     Public Property HeaderTransactions() As EntityCollection(Of HeaderTransaction)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of HeaderTransaction)("COFABONIDatabaseModel.FK_HeaderTransaction_MsUser", "HeaderTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of HeaderTransaction)("COFABONIDatabaseModel.FK_HeaderTransaction_MsUser", "HeaderTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="COFABONIDatabaseModel", Name:="Product")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Product
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Product object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    ''' <param name="stock">Initial value of the Stock property.</param>
    ''' <param name="price">Initial value of the Price property.</param>
    Public Shared Function CreateProduct(id As Global.System.Byte, name As Global.System.String, stock As Global.System.Int32, price As Global.System.Decimal) As Product
        Dim product as Product = New Product
        product.Id = id
        product.Name = name
        product.Stock = stock
        product.Price = price
        Return product
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Byte
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Byte
    Private Partial Sub OnIdChanging(value As Global.System.Byte)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Stock() As Global.System.Int32
        Get
            Return _Stock
        End Get
        Set
            OnStockChanging(value)
            ReportPropertyChanging("Stock")
            _Stock = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Stock")
            OnStockChanged()
        End Set
    End Property

    Private _Stock As Global.System.Int32
    Private Partial Sub OnStockChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnStockChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Price() As Global.System.Decimal
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Global.System.Decimal
    Private Partial Sub OnPriceChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Picture() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_Picture)
        End Get
        Set
            OnPictureChanging(value)
            ReportPropertyChanging("Picture")
            _Picture = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Picture")
            OnPictureChanged()
        End Set
    End Property

    Private _Picture As Global.System.Byte()
    Private Partial Sub OnPictureChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OnPictureChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("COFABONIDatabaseModel", "FK_DetailTransaction_Product", "DetailTransaction")>
     Public Property DetailTransactions() As EntityCollection(Of DetailTransaction)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DetailTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_Product", "DetailTransaction")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DetailTransaction)("COFABONIDatabaseModel.FK_DetailTransaction_Product", "DetailTransaction", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


